#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

# Install NodeJS LTS
/.nvm/nvm.sh install --lts

# Change working directory to project root
cd $SCRIPT_DIR/../../

# Install project dependencies
npm i
